### ISSUE TITLE
tsconfig 타입체크 

### ISSUE THREAD

**Issue by leobang17** [cau-ts-study/son-announcer#3]
`noImplicitAny`랑 `strictNullChecks`를 true로 하는게 어떰 ?

**Comment by dkile** [comment]
strict: true하면 저거 밑에 있는 타입 체킹 옵션들 다 true지 않나?

**Comment by leobang17** [comment]
@dkile 오우,,, 몰랐는데 찾아보니까 맞네 ㄱㅅㄱㅅ
